# Generated by Django 3.0.5 on 2020-04-28 03:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('team', '0001_initial'),
        ('goals', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Standup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('person', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='team.Person')),
            ],
        ),
        migrations.CreateModel(
            name='WorkingOn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.Goal')),
                ('standup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standups.Standup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Blocker',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.Goal')),
                ('standup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standups.Standup')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Accomplishment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.CharField(max_length=500)),
                ('goal', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='goals.Goal')),
                ('standup', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='standups.Standup')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
